In [21]:
import os
from PIL import Image
import numpy as np
from numpy.linalg import norm, pinv
np.set_printoptions(precision=12, suppress=True)

In [22]:
consider_distort = False # flag whether to consider distortion
zoomed_coords = True # whether to divide coordinates by 5 or not (zoomed coords or not)

In [23]:
folder_name = 'data/star_coords/spring2016_txt/' # folder with coords files

In [24]:
# 20160218
# fnames = [
#     '20160218-201934-437.txt',
#     '20160218-211934-484.txt'
# ]

# 20160219
fnames = [
    '20160219-001934-484.txt',
    '20160219-021934-593.txt',
    '20160219-041934-593.txt'
]

# 20160311
# fnames = [
#     '20160311-020811-125.txt',
#     '20160311-030811-125.txt'
# ]

In [25]:
if consider_distort:
    print "consider_distort is True!"

In [26]:
coords_list = []
for fname in fnames:
    piece = np.loadtxt(folder_name + os.sep + fname)
    coords_list.append(piece)

coords = np.vstack(coords_list)
print 'Zoomed In Star coordinates pairs:\n', coords, '\n'

if zoomed_coords:
    coords /= 5.0
    coords = coords.round()
    print 'Normal Star coordinates pairs:\n', coords

Zoomed In Star coordinates pairs:
[[ 6449.   748.  7662.   888.]
 [ 5107.   906.  6279.  1084.]
 [ 4334.  1784.  5504.  1981.]
 [ 4082.  1798.  5257.  2000.]
 [ 4239.  3179.  5426.  3381.]
 [ 4216.  3276.  5405.  3481.]
 [ 3522.  3067.  4703.  3278.]
 [ 3273.  4528.  4471.  4738.]
 [ 2273.  4615.  3476.  4823.]
 [ 1569.  3144.  2777.  3364.]
 [ 4901.  1553.  6074.  1741.]
 [ 5173.  3044.  6374.  3239.]
 [ 4268.  3959.  5462.  4170.]
 [ 2848.  3062.  4037.  3275.]
 [ 3989.  4895.  5192.  5107.]
 [ 2038.  3885.  3241.  4099.]
 [ 1507.  1311.  2706.  1569.]
 [  889.  2208.  2118.  2458.]
 [ 4919.  3253.  6120.  3457.]
 [ 3505.  3345.  4689.  3554.]
 [ 3522.  3383.  4702.  3593.]
 [ 2743.  2821.  3927.  3038.]
 [ 1720.  2239.  2920.  2477.]
 [ 1583.  1260.  2777.  1518.]
 [ 5512.   199.  6690.   362.]] 

Normal Star coordinates pairs:
[[ 1290.   150.  1532.   178.]
 [ 1021.   181.  1256.   217.]
 [  867.   357.  1101.   396.]
 [  816.   360.  1051.   400.]
 [  848.   636.  1085.   676.]
 [

In [27]:
lX = coords[:, 0] # leftX coordinates
lY = coords[:, 1] # leftY coordinates
rX = coords[:, 2] # rightX coordinates
rY = coords[:, 3] # rightY coordinates

N = coords.shape[0] # number of pairs of points
M = coords.shape[1] # lX, lY, rX, rY == 4
print 'Number of Star coordinates pairs:', N

Number of Star coordinates pairs: 25


In [28]:
xi = np.zeros(2*N)

num_coeffs = 2
if consider_distort:
    num_coeffs = 8

z = np.zeros(num_coeffs)
arr = np.zeros((2*N, num_coeffs)) # matrix A
print 'Number of coefficients:', num_coeffs

Number of coefficients: 2


In [29]:
for i in xrange(N): # fill the xi vector
    xi[2*i] = rX[i] - lX[i]
    xi[2*i + 1] = rY[i] - lY[i]

In [30]:
if consider_distort:
    im = Image.open('data/stars/2016spring/mod_'+ fnames[0][:-4] +'-1.png')
    x_c = im.width / 2.0
    y_c = im.height / 2.0
    for i in xrange(N): # fill the A matrix
        dist_l = (lX[i]-x_c)**2 + (lY[i]-y_c)**2
        dist_r = (rX[i]-x_c)**2 + (rY[i]-y_c)**2

        zx1 = (lX[i] - x_c) * dist_l
        zx2 = (rX[i] - x_c) * dist_r
        arr[2*i] = [lX[i], lY[i], 0, 0, 1, 0, -zx1, zx2]

        zy1 = (lY[i] - y_c) * dist_l
        zy2 = (rY[i] - y_c) * dist_r
        arr[2*i + 1] = [0, 0, lX[i], lY[i], 0, 1, -zy1, zy2]

else:
    for i in xrange(N): # fill the A matrix
        arr[2*i] = [1, 0]

        arr[2*i + 1] = [0, 1]

In [31]:
np.set_printoptions(precision=2, suppress=True)
print 'A:\n', arr, '\n'
print 'xi:\n', xi
np.set_printoptions(precision=12, suppress=True)

A:
[[ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 0.  1.]] 

xi:
[ 242.   28.  235.   36.  234.   39.  235.   40.  237.   40.  238.   41.
  237.   43.  239.   42.  240.   42.  241.   44.  235.   37.  240.   39.
  238.   42.  237.   43.  240.   42.  240.   43.  240.   52.  246.   50.
  240.   40.  237.   42.  236.   42.  236.   44.  240.   47.  238.   52.
  236.   32.]


In [32]:
p_arr = pinv(arr)
z = np.dot(p_arr, xi)
z = np.hstack([1,0,0,1, z])
print 'Affine coefficients: \n', z

Affine coefficients: 
[   1.      0.      0.      1.    238.28   41.68]


In [33]:
sigma = 2 # 2 pix error
I = np.eye(2*N)

print 'cond(A): ', np.linalg.cond(arr)
proba = (2*N - num_coeffs) / norm( np.dot(I - np.dot(arr, p_arr), xi) )**2
sig_theory = (1 / proba)**0.5

print 'Probability:', proba
print 'Sigma theory:', sig_theory
print 'Sigma practice', sigma

cond(A):  1.0
Probability: 0.0557828188918
Sigma theory: 4.23398945047
Sigma practice 2


In [34]:
res_fname = 'results/spring2016/'

if consider_distort:
    res_fname += 'affdis_coeffs_shots'
else:
    res_fname += 'affine_coeffs_shots'

res_fname += str(len(fnames)) + '_' + fnames[0]

In [35]:
np.savetxt(res_fname, z, fmt="%.10f")
print 'Coeffs are saved to:', res_fname

Coeffs are saved to: results/spring2016/affine_coeffs_shots3_20160219-001934-484.txt
